### ISSUE TITLE
Happy New Year, here is a bug

### ISSUE THREAD

**Issue by wright13** [nationalparkservice/NPSdataverse#27]
**Describe the bug**
After updating QCkit and trying to load NPSdataverse, I get an error that the previous version of QCkit can't be unloaded because it's imported by DPchecker.
This is probably at least in part the fault of my last pull request - happy to help troubleshoot if it's not an obvious fix.

**To Reproduce**
Loaded NPSdataverse and received a message that QCkit (v0.1.1) is out of date.
Unloaded NPSdataverse and installed QCkit v0.1.3 from github.
Re-loaded NPSdataverse.

**Screenshots**
![image](https://github.com/nationalparkservice/NPSdataverse/assets/6853454/cdccd270-b57b-4ad7-8b0b-2253de48144e)

**Comment by wright13** [comment]
works fine after loading NPSdataverse a second time though

**Comment by wright13** [comment]
never mind, after restarting rstudio, I now get this every time I try to load npsdataverse:
![image](https://github.com/nationalparkservice/NPSdataverse/assets/6853454/7ab85e62-7695-4f73-a909-4aaee1bad95e)

loading each package individually seems to work though

**Comment by RobLBaker** [comment]
Yes, I think this has something to do with the package reimport. Probably worth backing off of that concept and just making them dependencies.
