### ISSUE TITLE
NPSdataverse should point to a specific release of EMLassemblyline

### ISSUE THREAD

**Issue by RobLBaker** [nationalparkservice/NPSdataverse#32]
Currently, NPSdataverse points to the development version of EMLassemblyline on github. This means that if any changes are made to EAL, it could break NPSdataverse. Instead it would be better to point to the most up to date version/release of EAL. Then if changes are made to EAL we will have time to account for them in NPSdataverse instead of having it all come crashing down.

**Comment by taroNPS** [comment]
Hi Rob, I was wondering if this issue was fixed? I tried installing the npsdataverse package, and kept on running into the ERROR: dependency 'taxonomyCleanr' is not available for package 'EMLassemblyline'. I worked around this by installing the "taxize" as well as the "bold" package separately before running the install npsdataverse code again. Hope this was an acceptable work around.

**Comment by RobLBaker** [comment]
Hi Taro! No, it isn't fixed yet. The issue is that the bold package has been booted off of CRAN. In addition, there have been some breaking API changes that effect taxize.  Its unfortunately not something that we can remedy from our end; we just have to wait for the developers of those packages to address the issues. 

On the upside, they are aware of the problems and appear to be making progress on them: https://github.com/ropensci/taxize/issues/938

While we are waiting on a permanent fix, you can use the following code [as suggested by Colin Smith](https://github.com/EDIorg/taxonomyCleanr/issues/52) to install bold and taxize from github rather than CRAN:

```install.packages("remotes")
library(remotes)

install_github("ropensci/taxize")
install_github("EDIorg/taxonomyCleanr")
```
However, I have not tested these installations, and I don't know to what degree they will or will not work. I imagine if part of the reason that packages are getting kicked off of CRAN is because they have not been updated to deal with underlying API changes, unless the github versions have been updated (which they very well may have), you might find limited functionality, especially as pertains to taxonomy.

At any rate, that code should get you up and running and allow you to install and load NPSdataverse.
