### ISSUE TITLE
Sarah comments

### ISSUE THREAD

**Issue by wright13** [nationalparkservice/NPSdataverse#5]
We should break this stuff out into individual issues eventually...

- May want to link to NPSdataverse package collection from each individual package's readme
- If we want fxn names to conform to tidyverse style guide (snake_case), better to do it now than later.
- We should (maybe?) come up with a convention for organizing functions in the R folder. 
	- I'm kind of leaning towards one function per file for small-ish packages because it's easier to see what functions are present. Unexported fxns could all go into a utils.R file.
	- For larger packages, maybe plan out what categories of functions will be in the package (e.g. validation, read/write, metadata creation, etc) and break files up that way. Downside of this is that there will inevitably be functions that don't fall neatly into one category, and those become hard to find. Documentation helps though.
- Unit tests are a good idea
- We should try out pkgdown! https://pkgdown.r-lib.org/index.html
- Should NPSdataverse_attach() silently return to_load?

**Comment by RobLBaker** [comment]
1) links to repos added
2) updated constituent NPS packages to snake_case
3a) conventions: discussed. ongoing.
3b) definitely needs improvement. Incorporated into development moving forward
4) I'm going to wait and see how you implement this first, @wright13 
5) Done! Or at least attempted for a subset of NPSdataverse packages.
6) Done.
