### ISSUE TITLE
Cannot open 'https://api.github.com/repos/nationalparkservice/NPSdataverse/tarball/HEAD'

### ISSUE THREAD

**Issue by garethrowell** [nationalparkservice/NPSdataverse#6]
[Running R version 4.2.0; devtools version 2.4.5, Rtools version 2.4.0]

This is my first attempt in loading NPSdataverse...

> devtools::install_github("nationalparkservice/NPSdataverse")
Downloading GitHub repo nationalparkservice/NPSdataverse@HEAD

Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/nationalparkservice/NPSdataverse/tarball/HEAD'

I am able to manually open the URL and download the tarball (nationalparkservice-NPSdataverse-07be839.tar.gz)

**Comment by RobLBaker** [comment]
I believe I've run into this before. I think the problem has to do with Rstudio and how it handdles https connections. Prior to installing from github, by running the following code in R:

>options(download.file.method = "wininet")

This is supposed to be the default method file download method in Rstudio, but for some reason it often gives me trouble. This bit of code should update your .Rprofile file and allow you to download the package.  If it doesn't work, please let me know.
